SOURCES := build/swig/sqlite_wrap.c \
		../native/sqlite3_wrap_manual.c \
		../native/intarray.c \
		../sqlite/sqlite3.c

JAVA_CMD ?= java
CFLAGS ?= -O3
CC ?= gcc
SQLITE_CFLAGS := \
		-I../sqlite \
		-DNDEBUG -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_FTS3 \
		-DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_MEMORY_MANAGEMENT \
		-DSQLITE_ENABLE_STAT2 -DHAVE_READLINE=0 -DSQLITE_THREADSAFE=1 \
		-DSQLITE_THREAD_OVERRIDE_LOCK=-1 -DTEMP_STORE=1 \
		-DSQLITE_OMIT_DEPRECATED -DSQLITE_OS_UNIX=1 \
		-DSQLITE_ENABLE_RTREE=1

