all: build/dist/libsqlite4java-linux-custom.so

include common.mk

build/dist/libsqlite4java-linux-custom.so: $(JNI_SOURCES) $(SQLITE_SOURCES)
	$(CC) $(CFLAGS) $(JAVA_CFLAGS) $(SQLITE_CFLAGS) -fPIC -shared \
		-o $@ $^ $(SQLITE_LIBS)

