all: build/dist/libsqlite4java-osx-custom.jnilib

include common.mk

build/dist/libsqlite4java-osx-custom.jnilib: $(JNI_SOURCES) $(SQLITE_SOURCES)
		$(CC) $(CFLAGS) $(JAVA_CFLAGS) $(SQLITE_CFLAGS) \
		-arch i386 -arch x86_64 -Xarch_i386 -m32 -Xarch_x86_64 -m64 \
		-mmacosx-version-min=10.5 -DMAC_OS_X_VERSION_MIN_REQUIRED=1050 \
		-dynamiclib -o $@ $^ $(SQLITE_LIBS) \
		-framework JavaVM
	

